### PR TITLE
Update Gatsby Benchmark

### PR DESCRIPTION
**Pull request by graysonhicks**
I made some improvements to the Gatsby version to query and build things more efficiently.  It reduces the cold/warm build times for Gatsby by 25 and 40%, respectively.

What I changed:
- use Gatsby's Filesystem API to build the pages, instead of querying them in gatsby-node (too many fields were being fetched)
- changed query in PageLayout to only query the one MD item (it was querying all 1000 every time and using pageContext)

### CODE REVIEW

**Comment by graysonhicks** [comment]
Can we please get this merged and have the Gatsby numbers/graphic updated? @schickling

**Comment by schickling** [comment]
Hi @graysonhicks. Thanks a lot for the PR and follow-up comment.

To set expectations in terms of timing: I'm currently not working on Contentlayer full-time and will only be back focusing on it in about 2 weeks. Sorry for the delay.

**Review by seancdavis — CHANGES_REQUESTED** [review]
Hi @graysonhicks! Thank you for the pull request. Your Gatsby changes look good, and we can get this merged and update the results.

A couple quick changes:

1. Remove `.DS_Store`. Could you also please add it to `.gitignore`?
2. Remove the `package-lock.json` files. The project is using Yarn workspaces. I'll add a note on contributing when updating the README with the new results.

**Comment by graysonhicks** [comment]
@seancdavis Thanks Sean!  I've removed the lock files and `.DS_Store` and added `.DS_Store` to `.gitignore`.

**Review by seancdavis — APPROVED** [review]

**Pull request merged**
